/* Auto-generated by AmigaTools/cd32_make_bitmap.py from
 * cd32_gp.jpeg.  Do not edit by hand. */
#ifndef CD32_BITMAP_H
#define CD32_BITMAP_H

#define CD32_BMP_W       640
#define CD32_BMP_H       140
#define CD32_BMP_DEPTH   4
#define CD32_BMP_COLORS  16
#define CD32_BMP_BWIDTH  80

extern const unsigned short cd32_palette[CD32_BMP_COLORS];
extern const unsigned char cd32_plane0[CD32_BMP_BWIDTH * CD32_BMP_H];
extern const unsigned char cd32_plane1[CD32_BMP_BWIDTH * CD32_BMP_H];
extern const unsigned char cd32_plane2[CD32_BMP_BWIDTH * CD32_BMP_H];
extern const unsigned char cd32_plane3[CD32_BMP_BWIDTH * CD32_BMP_H];

#endif
