#!/usr/bin/env python3
"""Convert cd32_gp.jpeg into Amiga-friendly planar bitmap data.

Output:
  cd32_bitmap.h  -- extern declarations for the palette and the
                    four bitplane byte arrays.
  cd32_bitmap.c  -- the actual static const arrays embedded in the
                    risergamepad binary.

Target: Hi-Res 640x200, 16 colours (4 bitplanes).  Bit order is
MSB-first within each byte (= standard Amiga planar layout).
"""

import os
import sys
from PIL import Image

SRC = os.path.join(os.path.dirname(__file__), "..", "cd32_gp.png")
HDR = os.path.join(os.path.dirname(__file__), "cd32_bitmap.h")
C   = os.path.join(os.path.dirname(__file__), "cd32_bitmap.c")
PREVIEW = os.path.join(os.path.dirname(__file__), "cd32_bitmap_preview.png")

W, H = 640, 140
# Hi-Res non-interlaced doubles each scanline vertically on the monitor,
# so 640x140 storage displays at 640x280 monitor pixels = ~2.3:1 aspect,
# matching the cropped controller photo.
DEPTH = 4
COLORS = 1 << DEPTH         # 16
BWIDTH = W // 8             # 80 bytes per row per plane


def rgb_to_amiga4(r: int, g: int, b: int) -> int:
    """8-bit RGB -> Amiga 12-bit RGB4 (0x0RGB, each component 0..15)."""
    return ((r >> 4) << 8) | ((g >> 4) << 4) | (b >> 4)


def main() -> int:
    if not os.path.exists(SRC):
        print(f"error: source image {SRC} not found", file=sys.stderr)
        return 1

    # cd32_gp.png is already cropped to the controller (3161x1385,
    # ~2.28:1), so just resize.  Composite over white in case the PNG
    # has alpha so the body keeps a clean background colour.
    src = Image.open(SRC)
    if src.mode in ("RGBA", "LA"):
        bg = Image.new("RGB", src.size, (0xF0, 0xF0, 0xF0))
        bg.paste(src, mask=src.split()[-1])
        img = bg
    else:
        img = src.convert("RGB")
    print(f"source {img.size}")

    img = img.resize((W, H), Image.LANCZOS)

    # Force a palette that includes the four CD32 button colours plus
    # the AMIGA logo red.  Background / body / shadows fill the rest
    # via adaptive quantisation against this seed palette.
    seed_colors = [
        (0xF0, 0xF0, 0xF0),   # near-white background
        (0x00, 0x00, 0x00),   # black
        (0x60, 0x60, 0x68),   # mid grey body
        (0x40, 0x40, 0x48),   # dark grey body shadow
        (0xA0, 0xA0, 0xA8),   # light grey body highlight
        (0xE0, 0x10, 0x10),   # red button / AMIGA logo
        (0x00, 0xA0, 0x40),   # green button
        (0xF0, 0xD0, 0x00),   # yellow button
        (0x00, 0x40, 0xE0),   # blue button
    ]
    pal_bytes = []
    for r, g, b in seed_colors:
        pal_bytes += [r, g, b]
    # Pad to 256 entries (PIL palette requirement)
    pal_bytes += [0] * (256 * 3 - len(pal_bytes))
    pal_ref = Image.new("P", (1, 1))
    pal_ref.putpalette(pal_bytes)

    pal_img = img.quantize(palette=pal_ref,
                            dither=Image.Dither.NONE)
    pal_img.save(PREVIEW)
    print(f"preview: {PREVIEW}")

    pixels = list(pal_img.getdata())
    pal = pal_img.getpalette()[:COLORS * 3]

    # Build 4 bitplanes.  For each pixel value v in 0..15, bit n of v
    # goes to plane n.  Within each plane, bit 7 of byte 0 is the
    # leftmost pixel of the row.
    planes = [[0] * (BWIDTH * H) for _ in range(DEPTH)]
    for y in range(H):
        for x in range(W):
            v = pixels[y * W + x]
            byte_idx = y * BWIDTH + (x >> 3)
            bit = 7 - (x & 7)
            for p in range(DEPTH):
                if v & (1 << p):
                    planes[p][byte_idx] |= 1 << bit

    palette_amiga = []
    for i in range(COLORS):
        r, g, b = pal[i * 3 : i * 3 + 3]
        palette_amiga.append(rgb_to_amiga4(r, g, b))

    with open(HDR, "w") as f:
        f.write("/* Auto-generated by AmigaTools/cd32_make_bitmap.py from\n"
                " * cd32_gp.jpeg.  Do not edit by hand. */\n")
        f.write("#ifndef CD32_BITMAP_H\n#define CD32_BITMAP_H\n\n")
        f.write(f"#define CD32_BMP_W       {W}\n")
        f.write(f"#define CD32_BMP_H       {H}\n")
        f.write(f"#define CD32_BMP_DEPTH   {DEPTH}\n")
        f.write(f"#define CD32_BMP_COLORS  {COLORS}\n")
        f.write(f"#define CD32_BMP_BWIDTH  {BWIDTH}\n\n")
        f.write("extern const unsigned short cd32_palette[CD32_BMP_COLORS];\n")
        f.write("extern const unsigned char cd32_plane0[CD32_BMP_BWIDTH * "
                "CD32_BMP_H];\n")
        f.write("extern const unsigned char cd32_plane1[CD32_BMP_BWIDTH * "
                "CD32_BMP_H];\n")
        f.write("extern const unsigned char cd32_plane2[CD32_BMP_BWIDTH * "
                "CD32_BMP_H];\n")
        f.write("extern const unsigned char cd32_plane3[CD32_BMP_BWIDTH * "
                "CD32_BMP_H];\n")
        f.write("\n#endif\n")

    with open(C, "w") as f:
        f.write("/* Auto-generated by AmigaTools/cd32_make_bitmap.py from\n"
                " * cd32_gp.jpeg.  Do not edit by hand. */\n")
        f.write('#include "cd32_bitmap.h"\n\n')

        f.write("const unsigned short cd32_palette[CD32_BMP_COLORS] = {\n   ")
        for i, c in enumerate(palette_amiga):
            f.write(f" 0x{c:04X},")
            if (i + 1) % 8 == 0:
                f.write("\n   ")
        f.write("\n};\n\n")

        for p in range(DEPTH):
            f.write(f"const unsigned char cd32_plane{p}"
                    f"[CD32_BMP_BWIDTH * CD32_BMP_H] = {{\n   ")
            for i, b in enumerate(planes[p]):
                f.write(f" 0x{b:02X},")
                if (i + 1) % 16 == 0:
                    f.write("\n   ")
            f.write("\n};\n\n")

    print(f"wrote: {HDR}")
    print(f"wrote: {C}")
    print(f"palette ({COLORS} entries):")
    for i, c in enumerate(palette_amiga):
        r = (c >> 8) & 0xF
        g = (c >> 4) & 0xF
        bl = c & 0xF
        print(f"  {i:2d}: 0x{c:04X}  R={r:2d} G={g:2d} B={bl:2d}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
