/* risergamepad-gui.c -- fullscreen GUI variant of the learn command.
 *
 * Opens a custom 320x256 screen with a small fixed palette and a
 * borderless backdrop window covering it.  Draws a stylised pixel-art
 * CD32 gamepad and walks the user through mapping each colour /
 * function button on the picture to a button on their USB pad.
 *
 * Flow is fully gamepad-driven:
 *   button held  = capture for current slot
 *   D-pad DOWN   = skip this slot (leave unmapped)
 *   D-pad LEFT + any button = exit
 *
 * After all slots are captured the mappings are committed to the
 * firmware (auto-saved per slot) and the screen stays open in verify
 * mode -- pressing buttons on the gamepad lights up the mapped
 * picture buttons so the user can confirm everything.
 */

#include "amiga_min.h"
#include "cd32_bitmap.h"
#include <stdio.h>
#include <string.h>

/* Static BitMap pointing at the embedded planar data from
 * cd32_bitmap.c (auto-generated by AmigaTools/cd32_make_bitmap.py). */
static struct BitMap cd32_bm = {
    CD32_BMP_BWIDTH,
    CD32_BMP_H,
    0,
    CD32_BMP_DEPTH,
    0,
    {
        (PLANEPTR)0L,   /* filled in at runtime to avoid static-init
                         * const-vs-non-const cast warnings */
        0L, 0L, 0L, 0L, 0L, 0L, 0L
    }
};

extern const unsigned char cd32_plane0[];
extern const unsigned char cd32_plane1[];
extern const unsigned char cd32_plane2[];
extern const unsigned char cd32_plane3[];

/* Riser memory map -- same as risergamepad.c. */
#define RISER_BASE_ADDR  0x00BA0000UL
#define SLOTS            10
#define UNMAPPED         0xFFu
#define PAD1_REG_BASE    0x20
#define PAD2_REG_BASE    0x2A
#define PAD1_LIVE_DATA   0x10
#define PAD1_LIVE_EXTRA  0x11
#define PAD2_LIVE_DATA   0x12
#define PAD2_LIVE_EXTRA  0x13
#define SENTINEL_REG     0x16   /* reads 0xA5 when the riser bus path is alive */
static volatile unsigned char * const riser_gui =
    (volatile unsigned char *)RISER_BASE_ADDR;

#define CAP_ABORT  -1
#define CAP_SKIP   -2

#define MASK_LEFT     0x0002u
#define MASK_DOWN     0x0004u
#define MASK_DPAD     0x000Fu
#define MASK_BUTTONS  0xFFF0u

struct IntuitionBase *IntuitionBase = 0L;
struct GfxBase       *GfxBase       = 0L;

int cmd_gui(int pad, int demo);

/* ---- screen + palette ------------------------------------------------ */

/* Hi-Res 640x256, 4 bitplanes = 16 colours.  256 rows fully covers a
 * PAL display (no white strip below) while NTSC monitors simply clip
 * the bottom -- all visible content lives in the top 200 rows.  The
 * 640x140 photo is blitted at the top; the dark navy text strip runs
 * from y=140 all the way to the bottom so PAL doesn't show any gap. */
#define SCR_W   640
#define SCR_H   256
/* Push the photo down so the Workbench/screen title bar doesn't clip
 * the top of the controller. */
#define BMP_Y   20
#define SCR_D   CD32_BMP_DEPTH

/* Pens.  Indices 0..8 are filled by the generator (white, black,
 * greys, red, green, yellow, blue).  Indices 9..15 are unused in
 * the source image but we steal a few of them for UI overlays. */
#define PEN_WHITE   0
#define PEN_BLACK   1
#define PEN_GREY_M  2
#define PEN_GREY_D  3
#define PEN_GREY_L  4
#define PEN_RED     5
#define PEN_GREEN   6
#define PEN_YELLOW  7
#define PEN_BLUE    8
#define PEN_HIGHL   9   /* overlay highlight ring */
#define PEN_TXT_BG 10   /* dark blue strip behind prompt text */
#define PEN_TXT_FG 11   /* bright text on the strip */

/* Overlay-pen palette overrides applied after LoadRGB4. */
static void install_overlay_pens(struct ViewPort *vp)
{
    /* Bright purple highlight ring -- magenta-leaning (max red, less
     * blue) so it pops against the dark blue-grey controller body. */
    SetRGB4(vp, (LONG)PEN_HIGHL, (ULONG)15, (ULONG)0, (ULONG)12);
    /* Dark navy strip behind prompt text */
    SetRGB4(vp, (LONG)PEN_TXT_BG, (ULONG)1, (ULONG)1, (ULONG)3);
    SetRGB4(vp, (LONG)PEN_TXT_FG, (ULONG)15, (ULONG)15, (ULONG)15);
}

static struct NewScreen gui_newscreen = {
    0, 0,                       /* LeftEdge, TopEdge */
    SCR_W, SCR_H,               /* Width, Height */
    SCR_D,                      /* Depth */
    PEN_BLACK, PEN_WHITE,       /* DetailPen, BlockPen */
    V_HIRES,                    /* ViewModes -- Hi-Res non-interlaced */
    CUSTOMSCREEN,
    0L, 0L, 0L, 0L
};

static struct NewWindow gui_newwindow = {
    0, 0,                       /* LeftEdge, TopEdge */
    SCR_W, SCR_H,               /* Width, Height */
    PEN_BLACK, PEN_WHITE,
    IDCMP_CLOSEWINDOW | IDCMP_VANILLAKEY,
    WFLG_BORDERLESS | WFLG_BACKDROP | WFLG_ACTIVATE
        | WFLG_NOCAREREFRESH | WFLG_RMBTRAP,
    0L, 0L, 0L,
    0L,                         /* Screen -- filled in at runtime */
    0L,
    SCR_W, SCR_H, SCR_W, SCR_H,
    CUSTOMSCREEN
};

/* ---- pad picture layout --------------------------------------------- */

enum {
    PAD_FIRE1 = 0, PAD_FIRE2, PAD_FIRE3,
    PAD_PLAY, PAD_RW, PAD_FF,
    PAD_GREEN, PAD_YELLOW, PAD_RED, PAD_BLUE
};

typedef struct {
    int is_round;               /* 1 = disc, 0 = rectangle (for shoulders / PLAY) */
    WORD cx, cy, r;             /* round button geometry */
    WORD x, y, w, h;             /* rect button geometry */
    UBYTE color;                /* pen for the button face */
    int slot;
    const char *label;          /* drawn inside rect buttons */
} pad_button_t;

/* Button locations sit on top of where each real button appears in
 * cd32_bitmap_preview.png (640x140).  Highlight rings are drawn over
 * the bitmap at these positions. */
static const pad_button_t pad_buttons[] = {
    /* 4 colour buttons on the right wing */
    { 1, 506,  48, 12,   0,0,0,0, 0, PAD_GREEN,  0L },
    { 1, 565,  39, 12,   0,0,0,0, 0, PAD_YELLOW, 0L },
    { 1, 521,  77, 16,   0,0,0,0, 0, PAD_RED,    0L },
    { 1, 580,  69, 12,   0,0,0,0, 0, PAD_BLUE,   0L },
    /* Shoulder areas (RW left, FF right) along the top edge */
    { 0, 0,0,0,  74,  2,  110, 6, 0, PAD_RW, "<<" },
    { 0, 0,0,0,  453,  2,  110, 6, 0, PAD_FF, ">>" },
    /* PLAY -- the small horizontal slot on the centre bridge. */
    { 0, 0,0,0,  350, 93,  100, 12, 0, PAD_PLAY, "PLAY" },
};
#define N_PAD_BUTTONS  (sizeof(pad_buttons)/sizeof(pad_buttons[0]))

static const int gui_prompt_order[] = {
    PAD_RED, PAD_GREEN, PAD_BLUE, PAD_YELLOW,
    PAD_PLAY, PAD_RW, PAD_FF
};
#define N_PROMPTS  (sizeof(gui_prompt_order)/sizeof(gui_prompt_order[0]))

static const char *gui_slot_name(int slot)
{
    switch (slot) {
    case PAD_RED:    return "RED";
    case PAD_GREEN:  return "GREEN";
    case PAD_BLUE:   return "BLUE";
    case PAD_YELLOW: return "YELLOW";
    case PAD_PLAY:   return "PLAY";
    case PAD_RW:     return "RW";
    case PAD_FF:     return "FF";
    }
    return "?";
}

/* ---- drawing primitives --------------------------------------------- */

static void filled_rect(struct RastPort *rp, UBYTE pen,
                        WORD x1, WORD y1, WORD x2, WORD y2)
{
    SetAPen(rp, (LONG)pen);
    RectFill(rp, x1, y1, x2, y2);
}

static void outline_rect(struct RastPort *rp, UBYTE pen,
                         WORD x1, WORD y1, WORD x2, WORD y2)
{
    SetAPen(rp, (LONG)pen);
    Move(rp, x1, y1);  Draw(rp, x2, y1);
    Draw(rp, x2, y2);  Draw(rp, x1, y2);  Draw(rp, x1, y1);
}

static void draw_label(struct RastPort *rp, UBYTE pen,
                       WORD x, WORD y, const char *s)
{
    SetAPen(rp, (LONG)pen);
    SetDrMd(rp, (LONG)JAM1);
    Move(rp, x, y);
    Text(rp, (UBYTE*)s, (LONG)strlen(s));
}

/* Approximate filled circle (for the D-pad disc and round buttons),
 * crude but the pixel-art look matches.  Radius up to ~24. */
static void filled_disc(struct RastPort *rp, UBYTE pen,
                        WORD cx, WORD cy, WORD r)
{
    WORD y;
    long r2 = (long)r * r;
    SetAPen(rp, (LONG)pen);
    for (y = -r; y <= r; y++) {
        long y2 = (long)y * y;
        WORD x;
        if (y2 > r2) continue;
        for (x = r; x >= 0; x--) {
            if ((long)x*x + y2 <= r2) break;
        }
        if (x >= 0) RectFill(rp, cx - x, cy + y, cx + x, cy + y);
    }
}

/* Blit the embedded CD32 photo bitmap.  The strip above the photo
 * (y = 0 .. BMP_Y-1) gets filled with the text background colour so
 * the title bar overlays a clean band instead of stale pixels. */
static void draw_body(struct RastPort *rp)
{
    if (BMP_Y > 0) {
        filled_rect(rp, PEN_TXT_BG, 0, 0, SCR_W - 1, BMP_Y - 1);
    }
    BltBitMapRastPort(&cd32_bm, (LONG)0, (LONG)0,
                      rp, (LONG)0, (LONG)BMP_Y,
                      (LONG)CD32_BMP_W, (LONG)CD32_BMP_H,
                      (ULONG)0xC0);
}

/* Overlay-style highlight: draw a thick ring around the button (or a
 * rectangle outline for shoulder / PLAY) on top of the photo bitmap.
 * When not highlighted, do nothing -- the bitmap already shows the
 * button in its native colour. */
static void draw_pad_button(struct RastPort *rp, const pad_button_t *b,
                            int highlighted)
{
    if (!highlighted) return;
    SetAPen(rp, (LONG)PEN_HIGHL);
    if (b->is_round) {
        /* Two concentric ellipses for a thicker ring.  Hi-Res storage
         * pixels are ~2x as tall as wide on the monitor, so to draw a
         * visually round ring we need rx (in storage px) to be ~2x ry. */
        LONG ry = (LONG)b->r;
        LONG rx = ry * 2;
        DrawEllipse(rp, (LONG)b->cx, (LONG)(b->cy + BMP_Y), rx,     ry);
        DrawEllipse(rp, (LONG)b->cx, (LONG)(b->cy + BMP_Y), rx + 2, ry + 1);
    } else {
        WORD x1 = b->x, y1 = b->y + BMP_Y;
        WORD x2 = b->x + b->w, y2 = b->y + b->h + BMP_Y;
        outline_rect(rp, PEN_HIGHL, x1 - 1, y1 - 1, x2 + 1, y2 + 1);
        outline_rect(rp, PEN_HIGHL, x1 - 2, y1 - 2, x2 + 2, y2 + 2);
    }
}

static void draw_chrome(struct RastPort *rp, int pad,
                        const char *prompt, const char *hint)
{
    /* Bottom strip (below the photo) for status text. */
    filled_rect(rp, PEN_TXT_BG,
                0, CD32_BMP_H + BMP_Y, SCR_W - 1, SCR_H - 1);

    SetDrMd(rp, (LONG)JAM1);

    /* Title line (pad is unused now -- same title for either port). */
    draw_label(rp, PEN_TXT_FG, 8, CD32_BMP_H + BMP_Y + 12,
               "Map your USB gamepad buttons to the CD32 buttons");
    if (prompt) draw_label(rp, PEN_TXT_FG, 8, CD32_BMP_H + BMP_Y + 30, prompt);
    if (hint)   draw_label(rp, PEN_TXT_FG, 8, CD32_BMP_H + BMP_Y + 48, hint);
}

static void draw_pad(struct Window *win, int pad, int highlight_slot,
                     const char *prompt, const char *hint)
{
    struct RastPort *rp = win->RPort;
    int i;

    draw_body(rp);
    draw_chrome(rp, pad, prompt, hint);
    for (i = 0; i < (int)N_PAD_BUTTONS; i++) {
        int hl = (pad_buttons[i].slot == highlight_slot);
        draw_pad_button(rp, &pad_buttons[i], hl);
    }
}

/* ---- helpers shared with risergamepad.c logic ----------------------- */

static unsigned int gui_read_live(int pad)
{
    unsigned char d, e;
    if (pad == 1) {
        d = riser_gui[PAD1_LIVE_DATA];
        e = riser_gui[PAD1_LIVE_EXTRA];
    } else {
        d = riser_gui[PAD2_LIVE_DATA];
        e = riser_gui[PAD2_LIVE_EXTRA];
    }
    return ((unsigned int)e << 8) | (unsigned int)d;
}

static unsigned char gui_reg_addr(int pad, int slot)
{
    return (unsigned char)((pad == 1 ? PAD1_REG_BASE : PAD2_REG_BASE) + slot);
}

/* Restore the small bitmap area covered by a button's highlight ring
 * (so the next draw_pad_button(highlighted=1) call cleanly redraws on
 * top of the photo instead of stacking on a stale ring). */
static void erase_button_overlay(struct RastPort *rp,
                                 const pad_button_t *b)
{
    WORD x1, y1, x2, y2;
    if (b->is_round) {
        LONG ry = b->r;
        LONG rx = ry * 2;
        x1 = (WORD)(b->cx - rx - 3);
        y1 = (WORD)(b->cy - ry - 3 + BMP_Y);
        x2 = (WORD)(b->cx + rx + 3);
        y2 = (WORD)(b->cy + ry + 3 + BMP_Y);
    } else {
        x1 = (WORD)(b->x - 3);
        y1 = (WORD)(b->y - 3 + BMP_Y);
        x2 = (WORD)(b->x + b->w + 3);
        y2 = (WORD)(b->y + b->h + 3 + BMP_Y);
    }
    if (x1 < 0) x1 = 0;
    if (y1 < BMP_Y) y1 = BMP_Y;
    if (x2 >= SCR_W) x2 = SCR_W - 1;
    if (y2 >= BMP_Y + CD32_BMP_H) y2 = (WORD)(BMP_Y + CD32_BMP_H - 1);
    /* Source coords are in bitmap-local space (no BMP_Y), destination
     * in screen space. */
    BltBitMapRastPort(&cd32_bm,
                      (LONG)x1, (LONG)(y1 - BMP_Y),
                      rp, (LONG)x1, (LONG)y1,
                      (LONG)(x2 - x1 + 1), (LONG)(y2 - y1 + 1),
                      (ULONG)0xC0);
}

/* Wait for a button press, a skip combo, or an exit combo.  When
 * allow_skip == 0 the D-pad DOWN combo is ignored so the caller can
 * force a particular slot (e.g. RED / fire1) to be mapped.  hl_slot
 * is the slot currently being prompted -- in non-demo mode we slowly
 * flash its highlight ring to draw attention. */
static int gui_capture_button(struct Window *win, int pad, int demo,
                              int allow_skip, int hl_slot)
{
    unsigned int prev_btns = 0;
    int stable = 0;
    int candidate = -1;
    LONG demo_ticks = 60;     /* ~1.2 s per slot at 50 Hz */
    LONG flash_ticks = 30;    /* ~0.6 s on / 0.6 s off */
    int  show_ring  = 1;
    const pad_button_t *hl_btn = 0L;
    {
        int j;
        for (j = 0; j < (int)N_PAD_BUTTONS; j++) {
            if (pad_buttons[j].slot == hl_slot) {
                hl_btn = &pad_buttons[j];
                break;
            }
        }
    }

    for (;;) {
        struct IntuiMessage *msg;
        unsigned int w, dpad, btns;

        while ((msg = (struct IntuiMessage*)GetMsg(win->UserPort)) != 0L) {
            ULONG class = msg->Class;
            UWORD code  = msg->Code;
            ReplyMsg((struct Message*)msg);
            if (class == IDCMP_CLOSEWINDOW) return CAP_ABORT;
            if (class == IDCMP_VANILLAKEY
                && (code == 'q' || code == 'Q' || code == 27))
                return CAP_ABORT;
        }
        if (CheckSignal(SIGBREAKF_CTRL_C)) return CAP_ABORT;

        if (demo) {
            if (--demo_ticks <= 0) return CAP_SKIP;
            Delay((LONG)1);
            continue;
        }

        /* Slowly blink the prompt button's highlight ring. */
        if (hl_btn) {
            if (--flash_ticks <= 0) {
                show_ring = !show_ring;
                flash_ticks = 30;
                erase_button_overlay(win->RPort, hl_btn);
                if (show_ring) draw_pad_button(win->RPort, hl_btn, 1);
            }
        }

        w    = gui_read_live(pad);
        dpad = w & MASK_DPAD;
        btns = w & MASK_BUTTONS;

        if ((dpad & MASK_LEFT) && btns) return CAP_ABORT;

        if (allow_skip && (dpad & MASK_DOWN) && !btns) {
            while (gui_read_live(pad) & MASK_DPAD) {
                if (CheckSignal(SIGBREAKF_CTRL_C)) return CAP_ABORT;
                Delay((LONG)1);
            }
            return CAP_SKIP;
        }

        if (btns && !dpad) {
            int b;
            for (b = 4; b < 16; b++) {
                if (btns & (1u << b)) { candidate = b; break; }
            }
            if (btns == prev_btns) {
                if (++stable >= 3) {
                    int captured = candidate;
                    while (gui_read_live(pad) & MASK_BUTTONS) {
                        if (CheckSignal(SIGBREAKF_CTRL_C)) return CAP_ABORT;
                        Delay((LONG)1);
                    }
                    return captured;
                }
            } else {
                stable = 1;
            }
        } else {
            stable = 0;
            candidate = -1;
        }
        prev_btns = btns;

        Delay((LONG)1);
    }
}

static void gui_verify_mode(struct Window *win, int pad,
                            const unsigned char *src, int demo)
{
    unsigned int prev_btns = 0xFFFFFFFFu;
    int done = 0;
    int demo_idx = 0;
    LONG demo_ticks = 0;

    draw_pad(win, pad, -1,
             demo ? "Demo:  buttons light up in sequence."
                  : "Saved!  Press buttons -- they light up if mapped correctly.",
             demo ? "press Q to exit"
                  : "LEFT + button = exit");

    while (!done) {
        struct IntuiMessage *msg;
        unsigned int w, btns;

        while ((msg = (struct IntuiMessage*)GetMsg(win->UserPort)) != 0L) {
            ULONG class = msg->Class;
            UWORD code  = msg->Code;
            ReplyMsg((struct Message*)msg);
            if (class == IDCMP_CLOSEWINDOW) done = 1;
            else if (class == IDCMP_VANILLAKEY
                     && (code == 'q' || code == 'Q' || code == 27))
                done = 1;
        }
        if (CheckSignal(SIGBREAKF_CTRL_C)) break;

        if (demo) {
            if (--demo_ticks <= 0) {
                struct RastPort *rp = win->RPort;
                int i, hl_slot = gui_prompt_order[demo_idx];
                draw_body(rp);
                draw_chrome(rp, pad,
                    "Demo:  buttons light up in sequence.",
                    "press Q to exit");
                for (i = 0; i < (int)N_PAD_BUTTONS; i++) {
                    int hl = (pad_buttons[i].slot == hl_slot);
                    draw_pad_button(rp, &pad_buttons[i], hl);
                }
                demo_idx = (demo_idx + 1) % (int)N_PROMPTS;
                demo_ticks = 25;  /* ~0.5 s per button */
            }
            Delay((LONG)2);
            continue;
        }

        w    = gui_read_live(pad);
        btns = w & MASK_BUTTONS;
        if ((w & MASK_LEFT) && btns) { done = 1; break; }

        if (btns != prev_btns) {
            int i;
            struct RastPort *rp = win->RPort;
            draw_body(rp);
            draw_chrome(rp, pad,
                "Press buttons -- they light up if mapped correctly.",
                "LEFT + button = exit");
            for (i = 0; i < (int)N_PAD_BUTTONS; i++) {
                int slot = pad_buttons[i].slot;
                int s = (slot >= 0 && slot < SLOTS) ? src[slot] : UNMAPPED;
                int hl = (s != UNMAPPED) && (btns & (1u << s)) ? 1 : 0;
                draw_pad_button(rp, &pad_buttons[i], hl);
            }
            prev_btns = btns;
        }

        Delay((LONG)2);
    }
}

/* Same sentinel check as the command-line tool: $16 reads 0xA5 only
 * when the riser's bus path is alive; an absent board floats to 0xFF. */
static int gui_riser_present(void)
{
    return riser_gui[SENTINEL_REG] == 0xA5u;
}

/* Show a "board not found" message on the GUI screen and wait for the
 * user to quit.  Used in non-demo mode when no riser responds. */
static void gui_show_no_hardware(struct Window *win)
{
    struct RastPort *rp = win->RPort;

    draw_body(rp);
    filled_rect(rp, PEN_TXT_BG, 0, CD32_BMP_H + BMP_Y, SCR_W - 1, SCR_H - 1);
    SetDrMd(rp, (LONG)JAM1);
    draw_label(rp, PEN_TXT_FG, 8, CD32_BMP_H + BMP_Y + 12,
               "TF CD32 Riser not detected.");
    draw_label(rp, PEN_TXT_FG, 8, CD32_BMP_H + BMP_Y + 30,
               "No riser board responded -- check that it is fitted.");
    draw_label(rp, PEN_TXT_FG, 8, CD32_BMP_H + BMP_Y + 48,
               "press Q to exit");

    for (;;) {
        struct IntuiMessage *msg;
        while ((msg = (struct IntuiMessage*)GetMsg(win->UserPort)) != 0L) {
            ULONG class = msg->Class;
            UWORD code  = msg->Code;
            ReplyMsg((struct Message*)msg);
            if (class == IDCMP_CLOSEWINDOW) return;
            if (class == IDCMP_VANILLAKEY
                && (code == 'q' || code == 'Q' || code == 27)) return;
        }
        if (CheckSignal(SIGBREAKF_CTRL_C)) return;
        Delay((LONG)5);
    }
}

static int cmd_gui_run(struct Window *win, int pad, int demo)
{
    unsigned char new_src[SLOTS];
    int i, slot;
    char prompt[80];
    const char *hint_skip = demo
        ? "demo mode -- auto-advancing"
        : "DOWN = skip      LEFT + button = exit";
    const char *hint_required = demo
        ? "demo mode -- auto-advancing"
        : "this button is required      LEFT + button = exit";

    /* No live hardware to map against (and not faking it with demo
     * mode): tell the user on-screen rather than reading 0xFF garbage. */
    if (!demo && !gui_riser_present()) {
        gui_show_no_hardware(win);
        return 1;
    }

    for (i = 0; i < SLOTS; i++) new_src[i] = UNMAPPED;

    for (i = 0; i < (int)N_PROMPTS; i++) {
        int captured;
        int allow_skip;
        slot = gui_prompt_order[i];
        /* RED is fire1 -- every gamepad / joystick has at least one
         * button, so we never let the user leave it unmapped. */
        allow_skip = (slot != PAD_RED);

        sprintf(prompt, demo
                ? "Demo:  highlighting the %s button."
                : "Press the %s button on your gamepad.",
                gui_slot_name(slot));
        draw_pad(win, pad, slot, prompt,
                 allow_skip ? hint_skip : hint_required);

        captured = gui_capture_button(win, pad, demo, allow_skip, slot);
        if (captured == CAP_ABORT) return 1;
        if (captured == CAP_SKIP) continue;

        new_src[slot] = (unsigned char)captured;
        if (slot == PAD_RED) new_src[PAD_FIRE1] = (unsigned char)captured;
    }

    if (!demo) {
        for (i = 0; i < SLOTS; i++) {
            riser_gui[gui_reg_addr(pad, i)] = new_src[i];
        }
    }

    gui_verify_mode(win, pad, new_src, demo);
    return 0;
}

int cmd_gui(int pad, int demo)
{
    struct Screen *screen;
    struct Window *win;

    IntuitionBase = (struct IntuitionBase*)OpenLibrary("intuition.library", 36);
    if (!IntuitionBase) {
        printf("Couldn't open intuition.library (need 36+)\n");
        return 1;
    }
    GfxBase = (struct GfxBase*)OpenLibrary("graphics.library", 36);
    if (!GfxBase) {
        printf("Couldn't open graphics.library (need 36+)\n");
        CloseLibrary((struct Library*)IntuitionBase);
        return 1;
    }

    /* Bitplane source data must live in CHIP RAM -- the Amiga blitter
     * only reads chip memory.  Our cd32_plane* static arrays may end
     * up in fast RAM (especially on systems with expansion memory),
     * which makes BltBitMap read garbage.  Allocate one big chip-RAM
     * block, copy all four planes into it, and point our BitMap at
     * the copy. */
    {
        const ULONG plane_size = (ULONG)CD32_BMP_BWIDTH * (ULONG)CD32_BMP_H;
        UBYTE *chip = (UBYTE*)AllocMem(plane_size * 4UL, MEMF_CHIP);
        if (!chip) {
            printf("Couldn't allocate %lu bytes of CHIP RAM for "
                   "bitmap\n", plane_size * 4UL);
            CloseLibrary((struct Library*)GfxBase);
            CloseLibrary((struct Library*)IntuitionBase);
            return 1;
        }
        memcpy(chip,                       cd32_plane0, plane_size);
        memcpy(chip + plane_size,          cd32_plane1, plane_size);
        memcpy(chip + plane_size * 2UL,    cd32_plane2, plane_size);
        memcpy(chip + plane_size * 3UL,    cd32_plane3, plane_size);
        cd32_bm.Planes[0] = (PLANEPTR)chip;
        cd32_bm.Planes[1] = (PLANEPTR)(chip + plane_size);
        cd32_bm.Planes[2] = (PLANEPTR)(chip + plane_size * 2UL);
        cd32_bm.Planes[3] = (PLANEPTR)(chip + plane_size * 3UL);
    }

    screen = OpenScreen(&gui_newscreen);
    if (!screen) {
        printf("Couldn't open custom screen\n");
        CloseLibrary((struct Library*)GfxBase);
        CloseLibrary((struct Library*)IntuitionBase);
        return 1;
    }

    /* Load the bitmap's adaptive palette, then override the
     * unused high slots with overlay-UI pens. */
    {
        struct ViewPort *vp =
            (struct ViewPort *)((UBYTE*)screen + SCREEN_VIEWPORT_OFFSET);
        LoadRGB4(vp, cd32_palette, (LONG)CD32_BMP_COLORS);
        install_overlay_pens(vp);
    }

    gui_newwindow.Screen = screen;
    win = OpenWindow(&gui_newwindow);
    if (!win) {
        printf("Couldn't open backdrop window on custom screen\n");
        CloseScreen(screen);
        CloseLibrary((struct Library*)GfxBase);
        CloseLibrary((struct Library*)IntuitionBase);
        return 1;
    }

    cmd_gui_run(win, pad, demo);

    CloseWindow(win);
    CloseScreen(screen);
    if (cd32_bm.Planes[0]) {
        const ULONG plane_size = (ULONG)CD32_BMP_BWIDTH * (ULONG)CD32_BMP_H;
        FreeMem((APTR)cd32_bm.Planes[0], plane_size * 4UL);
    }
    CloseLibrary((struct Library*)GfxBase);
    CloseLibrary((struct Library*)IntuitionBase);
    return 0;
}
